void setupPantalla();
void drawInicio();
void drawMenuPrincipal();
void drawSelector(int cantidad, int seleccion);
void drawMenuRecetas();
void drawMaximoRecetas();
void drawInstruccionesAgregarReceta();
void drawPrueba();
void drawMensajeDestarando();
void drawMensajeCentrado(String palabra);
void drawMensajeNuevoPeso(int d1, int d2, int d3, int d4, int digito);
void drawErrorAgregarReceta();
void drawRecetaCorrecta(int nroReceta);
void drawSinRecetas();
void drawMostrarRecetas(int recetas[], int pagina, int aux);
void drawEliminarReceta(int d1, int d2, int digito);
void drawErrorEliminarReceta();
void drawErrorRecetaVacia();
void drawRecetaEliminada(int nroReceta);
void drawMarchaReceta(int d1, int d2, int digito);
void drawErrorMarchaReceta();